### ISSUE TITLE
Meeting Notes

### ISSUE THREAD

**Issue by tanmaysharma19** [UBC-MDS/obesity-explorer#2]
Documenting agendas and minutes from team meetings.

**Comment by tanmaysharma19** [comment]
Agenda:
1.	Discuss layout of the 4 quadrants in the sketch
2.	Discuss data wrangling to have pre-processed data to be used for all visualizations
 
Reflections:
1.	Optimize meeting structure.
2.	The team did a good job of laying out all the work and completing the requirements.
3.	Team is doing a good job of following the team contract.
 
Meeting minutes:
1.	Raf demo-ed the initial app development from week 1 (Obesity vs Smoking chart).
2.	Team discussed data-wrangling - if we should do rate calculations etc. on servers side vs
Client side, whether to have pre-processed data vs doing Altair transformations etc.
3.	Javairia demo-ed a plot for country rankings based on obesity rates, which relates to the bottom right plot in the proposal sketch.
4.	Team discussed chloropleth plot options and what visualizations can be shown on that plot.
5.	Team discussed the possibility of using other plotting libraries and agreed to work with Altair exclusively currently and exploring other libs if time permits.
 
Action Items:
1.	Each of the plots on the sketch - 1 item
            a.	Chloropleth (Raf)
            b.	Bar-chart (Javairia)
            c.	Time series plot (Dustin)
            d.	Scatter plot/ 3-factors (Tanmay)
2.	List of helper functions for repetitive wrangling and filtering tasks (Google docs?)
3.	Explore options to handle missing data as app dev continues
4.	Testing deployment on Heroku (Wednesday)
5.	Update GH issues and tasks for Milestone 2 submission
            a.	Update Readme as per instructions 
            b.	Explore transformations in Pandas vs Altair
            c.	Reflection document
            d.	Keep track of data/ code anomalies / test all dev work

**Comment by tanmaysharma19** [comment]
January 20, 2021 - Minutes

Agenda:
	1) Discuss the progress on the different plots.
	2) Discuss deployment to Heroku.
	3) Discuss next steps.

Meeting minutes:
	1) Raf demo-ed the progress on the Chloropleth plot and discussed data wrangling commonalities that all the team members could use.
	2) Dustin demo-ed the obesity trendline time-series plot and discussed adding different trendlines for the global obesity and regional obesity trendlines.
	3) Javairia demo-ed the bar-chart plot for the top countries based on obesity rate. 
	4) Tanmay requested another day to share progress on the scatter plot.
	5) Team discussed edits and optimizations to the different visualizations such as labels, opacity of trendlines, exclusion of origin from plots, changing axes' scale etc. 
	6) Team worked on deploying the app to Heroku and faced an error with half the plot not showing up when the app is deployed to Heroku.
	
Action Items:
	1) Finalize a csv with the country name and country code mappings.
	2) Develop the plots further as per the team discussion.
	3) Resolve the heroku deployment error where half the plot from app.py doesn't show up.
	4) Raf taking the lead to develop a data filtering function to do the common wrangling tasks.
	5) Handle the missing countries in the script e.g. USA etc.

**Comment by rtaph** [comment]
The active development of this app has moved to https://github.com/UBC-MDS/obesity-explorer-R

Please see that repo for the latest group meeting minutes.
