### ISSUE TITLE
Chloropleth plot

### ISSUE THREAD

**Issue by tanmaysharma19** [UBC-MDS/obesity-explorer#27]
- Top right corner plot in the sketch
- Global map and ranking/coloring based on rates of calculated variables.

**Comment by rtaph** [comment]
On track but need to fix problem with data cleaning that left some countries out (see #35). Still need to work out the mapping between plots to ensure interactivity.

![image](https://user-images.githubusercontent.com/9271253/105245541-de378f00-5b26-11eb-8b5f-f6538b6bc0eb.png)

**Comment by rtaph** [comment]
Done. Included in milestone 2 prototype.
