### ISSUE TITLE
Bar Chart plot

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/obesity-explorer#28]
- Bar chart plot for the bottom right corner 
 - Review of top countries with interactive widgets for year, gender

**Comment by jraza19** [comment]
Initial Creation:

![image](https://user-images.githubusercontent.com/70663258/105570849-83598f80-5d00-11eb-8740-17b74c2f7373.png)

**Comment by rtaph** [comment]
Done. Included in milestone 2 prototype.
