### ISSUE TITLE
Time series plot

### ISSUE THREAD

**Issue by tanmaysharma19** [UBC-MDS/obesity-explorer#29]
- Top left plot on the proposal sketch.
- explore visualizations for a time-series plot of obesity across 1975-2016.

**Comment by dusty736** [comment]
<img width="955" alt="Screen Shot 2021-01-21 at 5 58 25 PM" src="https://user-images.githubusercontent.com/14900360/105435534-5d55c180-5c12-11eb-850f-6a19bf79d380.png">

Issues to fix after Wednesday meeting:
- [ ] Fix the width
- [ ] Format y-axis to be percentage
- [ ] Layer the plot so the highlighted country is always on top
- [ ] Add distribution of final year of plot
- [ ] Implement radio button selector for sex
- [ ] Allow for multiple countries to be selected

**Comment by dusty736** [comment]
The time series plot has been completed, and the added y-axis distribution will be added in milestone 4.
