### ISSUE TITLE
Scatterplot/3 factors plot

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/obesity-explorer#30]
- Bottom left corner scatter plot(s)
- Consider obesity and factors associated with it

**Comment by tanmaysharma19** [comment]
Identified smoking, unemployment, and primary education completion as the factors to try and show their association with obesity. WIP.

![image](https://user-images.githubusercontent.com/25701154/105444283-62bb0800-5c22-11eb-8ab0-20d924161628.png)

**Comment by rtaph** [comment]
Done. Included in milestone 2 prototype.
