### ISSUE TITLE
Peer Feedback 

### ISSUE THREAD

**Issue by BruhatMusunuru** [UBC-MDS/obesity-explorer#53]
Hello developers of this Obesity Dashboard,

I am Bruhat. A policymaker for the state government of Baja California Sur, Mexico. Fast food chains from America have been expanding rapidly in our jurisdiction. Our medical advisers have brought up alarming concerns about Obesity in young adults caused by this expansion. We set out to find the long term effects of this expansion and your dashboard perfectly fit our needs. We have been trying analyse countries where this rapid expansion occurred and it's consequences on the obesity rate over the years.
-  Your plot on world obesity with years gave us good insights about the countries we were interested in and the filter by country option helped us isolate trends to our geographic needs. We were able to put together insights from your dashboard along with fast food chain's expansion data to back our medical adviser's hypothesis. 
-  If I could offer some constructive criticism, we found that the tool-tip feature in the world obesity plot was a little distracting and redundant as there was already an option to filter by the required country. 
- That being said, we really liked the dashboard and found it very useful.

**Comment by tanmaysharma19** [comment]
Thank you Bruhat, glad that you found our dashboard useful. Appreciate your feedback and suggestion. We've made some changes to the dashboard functionality with the R version of our app. We'll keep your thoughts in mind as we finalize our dashboard. Cheers!
