### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/obesity-explorer#54]
Halfway there! (or really 3/4 :) ) Great job on milestone 2. Your reflection was excellent and it's clear you've very thoroughly tested your app. I think overall, it looks great and does well in presenting a lot of information in a relatively compact way by making good use of interactivity. Most of the problems I noticed were already noted in your reflection, but here are a few additional ones:
- opacity a bit low on scatter plot 
- could consider fading/greying out countries in map rather than removing
- hanging color scale appears when no countries highlighted
- minor details that should be modified/clarified in design:
    - I don't have any great ideas on implementation, but would be nice to see the 3 variable filters (besides year) tied together in some way, as they are when treated as grouping variables.
    - maybe rename income group to clarify it's describing country not individual (unlike sex filter)
    
I also thought it might be useful to give my opinion on which of the points listed in your reflection would be most useful to fix/implement, so here are my top few listed roughly in order of importance:
1. Single year vertical line for selected year
2. Move year slider below time series plot
3. Fix missing data issue (map and scatter plot)
4. Map tooltip stopped working
5. If there is an empty selection, everything should be shown by default
6. Add trend lines to the factor plot

**Comment by rtaph** [comment]
Thank you for the feedback, Chris! We will use R for our final Milestone 4 Dash app, so all the above snags and recommendations have either been addressed or are moot.

Thanks for taking the time to help us make our app better :)
